<div class="page-margin"></div>
<div class="desktop-only">
    <h1>Welcome to <?php echo $sk['config']['site_name']; ?></h1>

    <div class="stories-container">
        <div class="stories-wrapper">
            <?php
            $stories = FA_getStories_all();

            if (is_array($stories) && count($stories) > 0) {

                foreach($stories as $sk['story']) {
                    echo FA_getPage('story/content-home');
                }
            }
            ?>
        </div>
        <div align="center">
            <div class="load-btn" onclick="FA_loadOldStories();">
                <i class="icon-reorder progress-icon hide"></i>
                <?php
                echo $lang['view_previous_posts_label'];
                ?>
            </div>
        </div>
    </div>

</div>
<!--<div class="float-right span35">
    <?php
/*    if (isset($_GET['tab2']) && $_GET['tab2'] == "password_reset") {
        
        if (isset($_GET['id']) && FA_isValidPasswordResetToken($_GET['id']) != false) {
    */?>
    <form class="welcome-form passwordreset-form" method="post">
        <div class="form-header">
            <?php /*echo $lang['reset_password_label']; */?>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="pr_password" placeholder="<?php /*echo $lang['new_password_label']; */?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-signin progress-icon"></i> <?php /*echo $lang['reset']; */?>
            </button>
        </div>
        <input type="hidden" name="pr_token" value="<?php /*echo $_GET['id']; */?>">
    </form>
    <?php
/*        } else {
    */?>
    <div class="welcome-form">
        <div class="form-header">
            Oops!
        </div>
        <div class="post-message">Invalid token!</div>
    </div>
    <?php
/*        }
    } else {
    */?>
    <?php
/*    if (isset($_GET['tab2']) && $_GET['tab2'] == "forgot_password") {
    */?>
    <form class="welcome-form forgotpass-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php /*echo $lang['forgot_password']; */?>?
            </div>
            <div class="float-right">
                <a href="<?php /*echo FA_smoothLink('index.php?tab1=welcome'); */?>"><?php /*echo $lang['log_in']; */?></a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="forgotpass_id" value="<?php /*echo $lang['login_id_label']; */?>" placeholder="<?php /*echo $lang['login_id_label']; */?>" data-placeholder="<?php /*echo $lang['login_id_label']; */?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-inbox progress-icon"></i> <?php /*echo $lang['reset_password_reset']; */?>
            </button>
        </div>
    </form>
    <?php
/*    } else {
    */?>
    <form class="welcome-form login-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php /*echo $lang['log_in']; */?>
            </div>
            <div class="float-right">
                <a href="<?php /*echo FA_smoothLink('index.php?tab1=welcome&tab2=forgot_password'); */?>"><?php /*echo $lang['forgot_password']; */?>?</a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="login_id" value="<?php /*echo $lang['login_id_label']; */?>" placeholder="<?php /*echo $lang['login_id_label']; */?>" data-placeholder="<?php /*echo $lang['login_id_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="password" name="login_password" placeholder="Password" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="checkbox" name="keep_logged_in" value="1"> Keep me logged in
            </div>
            
            <button class="submit-btn active"><i class="icon-signin progress-icon"></i> <?php /*echo $lang['log_in']; */?></button>
        </div>
    </form>
    <?php
/*    }
    */?>
    <form class="welcome-form signup-form" method="post">
        <div class="form-header"><?php /*echo $lang['sign_up_label']; */?></div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="name" placeholder="<?php /*echo $lang['fullname_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="text" name="username" placeholder="<?php /*echo $lang['username_label']; */?>" onkeyup="FA_checkUsername(this.value,0,'.check-username-result',false);" autocomplete="off">
                <div class="check-username-result"></div>
            </div>
            
            <div class="input-wrapper">
                <input type="password" name="password" placeholder="<?php /*echo $lang['password_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="text" name="email" placeholder="<?php /*echo $lang['email_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <select name="gender">
                    <option value=""><?php /*echo $lang['gender_label']; */?></option>
                    <option value="male"><?php /*echo $lang['gender_male_label']; */?></option>
                    <option value="female"><?php /*echo $lang['gender_female_label']; */?></option>
                </select>
            </div>

            <?php
/*            if ($sk['config']['reg_req_birthday'] == true) {
            */?>
            <div class="input-wrapper">
                <select class="birth-date-select" name="birthday[0]" style="width: 48px;">
                    <?php
/*                    for ($i = 1; $i < 32; $i++) {
                        
                        if ($i == $sk['user']['birth']['date']) {
                            $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                        } else {
                            $option = '<option value="' . $i . '">' . $i . '</option>';
                        }
                        
                        echo $option;
                    }
                    */?>
                </select>
                <select class="birth-month-select" name="birthday[1]" style="width: 98px;" onchange="FA_getMonthDays(this.value);">
                    <?php
/*                    foreach (FA_getMonths() as $month_number => $month_data) {
                        
                        if ($month_number == $sk['user']['birth']['month']) {
                            $option = '<option value="' . $month_number . '" selected>' . $month_data[1] . '</option>';
                        } else {
                            $option = '<option value="' . $month_number . '">' . $month_data[1] . '</option>';
                        }
                        
                        echo $option;
                    }
                    */?>
                </select>
                <select class="birth-year-select" name="birthday[2]" style="width: 65px;">
                    <?php
/*                    for ($i = date('Y')-100; $i < date('Y')-12; $i++) {
                        
                        if ($i == $sk['user']['birth']['year']) {
                            $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                        } else {
                            $option = '<option value="' . $i . '">' . $i . '</option>';
                        }
                        
                    echo $option;
                    }
                    */?>
                </select>
            </div>
            <script>
            function FA_getMonthDays(month_number) {
                var month = new Array();
                month[1] = 31;
                month[2] = 28;
                month[3] = 31;
                month[4] = 30;
                month[5] = 31;
                month[6] = 30;
                month[7] = 31;
                month[8] = 31;
                month[9] = 30;
                month[10] = 31;
                month[11] = 30;
                month[12] = 31;
                $('.birth-date-select').html('');
                
                for (i=1; i<=month[month_number]; i++) {
                    $('.birth-date-select').append('<option value="'+ i +'">'+ i +'</option>');
                }
            }
            </script>
            <?php
/*            }
            
            if ($sk['config']['reg_req_currentcity'] == true) {
            */?>
            <div class="input-wrapper">
                <input type="text" name="current_city" placeholder="<?php /*echo $lang['location_label']; */?>" autocomplete="off">
            </div>
            <?php
/*            }
            
            if ($sk['config']['reg_req_hometown'] == true) {
            */?>
            <div class="input-wrapper">
                <input type="text" name="hometown" placeholder="<?php /*echo $lang['hometown_label']; */?>" autocomplete="off">
            </div>
            <?php
/*            }
            
            if ($sk['config']['reg_req_about'] == true) {
            */?>
            <div class="input-wrapper">
                <textarea name="about" placeholder="<?php /*echo $lang['about_label']; */?>" autocomplete="off"></textarea>
            </div>
            <?php
/*            }

            if ($sk['config']['captcha'] == true) {
            $captcha = FA_createCaptcha();
            */?>
            <div class="input-wrapper">
                <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr>
                    <td width="85px" align="left" valign="middle">
                        <img class="captcha" src="<?php /*echo $sk['config']['site_url'] . '/' . $captcha['image']; */?>">
                    </td>
                    <td align="left" valign="middle">
                        <input type="text" value="<?php /*echo $lang['captcha_label']; */?>" placeholder="<?php /*echo $lang['captcha_label']; */?>" data-placeholder="<?php /*echo $lang['captcha_label']; */?>" autocomplete="off" data-copy-to=".register-captcha-input">
                        <input class="register-captcha-input" type="hidden" name="captcha">
                    </td>
                </tr>
                </table>
            </div>
            <?php /*} */?>
            
            <button class="submit-btn active"><i class="icon-angle-right progress-icon"></i> <?php /*echo $lang['sign_up_label'] ;*/?></button>
        </div>
    </form>
    <?php
/*    }
    */?>
    <div class="fb-button">
        <a href="<?php /*echo $sk['fb_login_url']; */?>">
            <i class="icon-facebook"></i>
            <span>Connect with Facebook</span>
        </a>
    </div>
</div>-->

<div class="float-clear"></div>
