<section id="news-ticker" class="ticker-wrapper divider-wrapper opaqued" data-parallax="scroll" data-image-src="<?php echo $sk['config']['theme_url']; ?>/assets/img/parallax/parallax_04.jpg">
	    
		    <div class="container">
		    	<div class="row">	
			    	<div class="col-md-2">
			    		<h4><strong>Search</strong> Dares</h4>
			    	</div>
			    	
	       <div id="header-search-input" class="col-md-11">
	            <div class="input-group">
	                <input type="text" class="  search-query form-control" placeholder="Enter Search Term" />
	                <span class="input-group-btn">
	                    <button class="btn btn-danger" type="button">
	                        <i class="fa fa-search"></i>
	                    </button>
	                </span>
	            </div>
	        </div>
        	
    	
		    	</div>
	    	</div>
	    </section>